version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: elt_postgres
    environment:
      POSTGRES_USER: elt_user
      POSTGRES_PASSWORD: elt_pass
      POSTGRES_DB: elt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nifi:
    image: apache/nifi:latest
    container_name: elt_nifi
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    restart: unless-stopped

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres
    container_name: elt_dbt
    volumes:
      - ./dbt:/usr/app
    working_dir: /usr/app
    entrypoint: ["tail", "-f", "/dev/null"]

  lightdash:
    image: lightdash/lightdash:latest
    container_name: elt_lightdash
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      LIGHTDASH_PROJECT_DIR: /usr/app
      PGUSER: elt_user
      PGPASSWORD: elt_pass
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: elt_db
    volumes:
      - ./dbt:/usr/app

  dbgate:
    image: dbgate/dbgate
    container_name: elt_dbgate
    ports:
      - "8082:3000"
    environment:
      CONNECTIONS: '[{"name":"Postgres","server":"postgres","user":"elt_user","password":"elt_pass","database":"elt_db","engine":"postgres"}]'

volumes:
  postgres_data:

