version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: elt_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: elt_user
      POSTGRES_PASSWORD: elt_pass
      POSTGRES_DB: elt_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  sqlmesh:
    image: python:3.11-slim
    container_name: elt_sqlmesh
    ports:
      - "8084:8000"
    volumes:
      - ./sqlmesh:/app/sqlmesh
    working_dir: /app/sqlmesh
    command: >
      sh -c "
        pip install sqlmesh[web] && \
        sqlmesh ui --host 0.0.0.0 --port 8000"

  lightdash:
    image: lightdash/lightdash:latest
    container_name: elt_lightdash
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - DBT_PROJECT_DIR=/app/sqlmesh
    volumes:
      - ./sqlmesh:/app/sqlmesh

  dbgate:
    image: dbgate/dbgate
    container_name: elt_dbgate
    restart: unless-stopped
    ports:
      - "8082:3000"

  nifi:
    image: apache/nifi:latest
    container_name: elt_nifi
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - ./nifi:/opt/nifi/nifi-current/conf

volumes:
  pgdata:
